config/routes.rb
# frozen_string_literal: true
Web3::Application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users

  scope path_names: { new: 'novo', edit: 'uredi', all: 'vse', search: 'isci' } do
    resources :inquiries, path: 'vprasanja' do
      get :all, on: :collection
      member do
        get :answer_question
        patch :answer
      end
    end
    resources :articles, path: 'clanki', only: [:index, :show] do
      get :search, on: :collection
    end
    resources :issues, path: 'revije', only: [:index, :show]
    resources :orders, path: 'narocila', only: [:new, :create] do
      get :successful, on: :collection, path: 'uspesno'
    end
    resources :copies, path: 'besedila'
    resources :authors, path: 'avtorji', only: [:show]
    resources :news, path: 'pd-vzgojiteljica'
  end

  get '/avtorji-spletne-aplikacije', to: 'pages#authors'
  get '/navodila', to: 'pages#editorial_instructions'

  namespace :admin do
    root to: 'admin#index'
    get :quantities, to: 'admin#quantities'
    get :controls, to: 'admin#controls'
    get :freeriders, to: 'admin#freeriders'
    get :regional, to: 'admin#regional'
    resources :duplicates do
      get :index_customers, on: :collection
      get :index_authors, on: :collection
      post :merge_customers, on: :member
      post :merge_authors, on: :collection
    end
    resources :entities
    resources :postal_costs, only: :index do
      get :calculate, on: :collection
      get :calculate_reward, on: :collection
    end
    resources :institutions, only: :index
    resources :posts
    resources :keywords do
      post :create_simple, on: :collection
    end
    resources :sections
    resources :articles
    resources :authors do
      post :create_simple, on: :collection
    end
    resources :issues do
      member do
        get :edit_cover
        get :edit_document
        patch :cover
        patch :document
      end
    end
    resources :letters do
      get :print, on: :member
    end
    resources :customers do
      post :new_from_order, on: :collection
      get :new_freerider, on: :collection
      post :create_freerider, on: :collection
      get :add_person, on: :member
      get :edit_person, on: :member
      post :create_person, on: :member
      patch :update_person, on: :member
      patch :unsubscribe, on: :member
      post :merge_in, on: :member
      get :email_ingestion, on: :collection
      get :email_ingestion_next, on: :collection
    end
    resources :labels, only: [:index, :show] do
      get :print, on: :collection
    end
    resources :subscribers
    resources :posts
    resources :subscriptions do
      get :patricija, on: :collection
      put :end_now, on: :member
      put :end_by_end_of_year, on: :member
      put :reinstate, on: :member
      post :new_from_order, on: :collection
    end
    resources :plans
    resources :batches
    resources :remarks
    resources :orders, only: [:index, :show]
    resources :order_forms do
      get :download, on: :member
      put :mark_processed, on: :member
      put :process_it, on: :member
    end
    resources :invoices do
      get :wizard, on: :collection
      get :print_wizard, on: :collection
      get :reversed, on: :collection
      get :unpaid, on: :collection
      get :due, on: :collection
      get :print, on: :member
      get :print_all, on: :collection
      get :einvoice, on: :member
      get :eenvelope, on: :member
      get :pdf, on: :member
      post :email, on: :member
      post :email_due, on: :member
      post :build_for_subscription, on: :collection
      post :build_partial_for_subscription, on: :collection
      put :reverse, on: :member
    end
    resources :offers do
      get :wizard, on: :collection
      get :print_wizard, on: :collection
      get :print, on: :member
      get :print_all, on: :collection
      get :pdf, on: :member
      post :create_for_customer, on: :collection
      post :email, on: :member
      post :email_due, on: :member
    end
    resources :bank_statements do
      post :parse, on: :member
    end
    resources :statement_entries, only: [:show] do
      post :match, on: :member
    end
  end

  # Public token route
  get '/:token', to: 'customers#public_show', as: :token
  post '/oddaja_narocilnice', to: 'customers#ingest_order_form', as: :ingest_order_form

  # You can have the root of your site routed with "root"
  # root to: 'copies#show', id: 'pages#index'
  root to: 'pages#index'
end

app/models/statement_entry.rb
# frozen_string_literal: true
class StatementEntry < ActiveRecord::Base
  belongs_to :bank_statement
  belongs_to :invoice

  validates_presence_of :account_holder, :account_number, :amount, :date, :reference, :bank_reference, :bank_statement
  validates_uniqueness_of :bank_reference

  monetize :amount_cents

  after_save :find_and_match_to_invoice, unless: :invoice

  scope :matched, -> { where(matched: true) }
  scope :unmatched, -> { where(matched: false) }

  def reference_parsed
    reference.strip.match(/^((\d{1,4})\-)?((\d{1,4})\-)(2014|2015|2016)$/)
  end

  def reference_match
    query = Invoice.arel_table[:payment_id].eq(reference.strip)
    query = query.or(Invoice.arel_table[:receipt_id].eq(reference.strip))
    invoices = Invoice.where(query)
  end

  def exact_match
    invoices = reference_match
    return unless invoices.length == 1
    return unless invoices.first.total == amount
    invoices.first
  end

  def matches
    if matched_invoice = exact_match
      return [matched_invoice]
    end

    return reference_match if reference_match.any?

    name_title_matches = account_holder.split("\n")
    if name_title_matches.length == 1
      name_title_matches = account_holder.split(',')
    end

    Invoice.unpaid.reject do |invoice|
      customer = invoice.customer
      reject = true

      # Name and title match.
      name_title_matches.compact.each do |name_title_match|
        next unless name_title_match.present?
        next unless customer

        if customer.name =~ Regexp.new(name_title_match.strip, 'gi')
          reject = false
        elsif customer.title =~ Regexp.new(name_title_match.strip, 'gi')
          reject = false
        elsif customer.address =~ Regexp.new(name_title_match.strip, 'gi')
          reject = false
        end
      end

      # Account number match.
      if customer.account_number =~ Regexp.new(account_number)
        reject = false
      elsif details =~ Regexp.new(invoice.receipt_id.to_s, 'gi')
        reject = false
      end

      reject
    end
  end

  def match_to_invoice!(matched_invoice)
    self.invoice = matched_invoice
    self.matched = true
    matched_invoice.statement_entries << self
    matched_invoice.paid_at = date
    matched_invoice.paid_amount = amount
    matched_invoice.bank_data = details
    matched_invoice.bank_reference = bank_reference
    matched_invoice.save
    save
  end

  def account_holder_parts
    account_holder? && account_holder.split(',')
  end

  def account_holder_title
    entity_parts[0]
  end

  def account_holder_subtitle
    entity_parts[1]
  end

  def account_holder_address
    entity_parts[2]
  end

  def account_holder_country
    entity_parts[3]
  end

  protected

  def find_and_match_to_invoice
    return if invoice
    return unless matched_invoice = exact_match
    match_to_invoice!(matched_invoice)
  end
end

app/controllers/admin/statement_entries_controller.rb
# frozen_string_literal: true
class Admin::StatementEntriesController < Admin::AdminController
  def show
    @unpaid_invoices = Invoice.unpaid.select(:id, :receipt_id).order(year: :desc, reference_number: :desc).map { |i| [i.receipt_id, i.receipt_id] }
    respond_with resource
  end

  def match
    invoice = Invoice.find_by(receipt_id: params[:invoice_id])
    unless invoice
      return redirect_to admin_statement_entry_path(resource), notice: "Can't find invoice"
    end

    resource.match_to_invoice!(invoice)
    respond_with resource, location: -> { admin_invoice_path(invoice) }
  end

  private

  def resource
    return unless params[:id]
    @statement_entry ||= StatementEntry.find(params[:id])
  end

  def set_page_title
    @page_title = 'Postavke izpiska'
  end
end

app/views/admin/statement_entries/show.html.erb
<script type="text/javascript">
  $(function() {
    $('#invoice_id').chosen({
      search_contains: true
    });
  });
</script>

<h2>
  Postavka <%= @statement_entry.id %>
  <small><%= link_to "Izpisek #{@statement_entry.bank_statement_id}", admin_bank_statement_path(@statement_entry.bank_statement_id) %></small>
</h2>

<div class="row">
  <div class="col-xs-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <strong>ID</strong>
        <p>
          <%= @statement_entry.bank_reference %>
        </p>
        <strong>Referenca</strong>
        <p><%= @statement_entry.reference %></p>
        <strong>Datum</strong>
        <p><%= l @statement_entry.date, format: :simple %></p>
        <strong>Znesek</strong>
        <p><%= number_to_currency @statement_entry.amount %></p>
      </div>
    </div>
  </div>
  <div class="col-xs-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <strong>Plačnik</strong>
        <p><%= simple_format @statement_entry.account_holder.split(',').join("\n") %></p>
        <strong>TRR</strong>
        <p><%= @statement_entry.account_number %></p>
        <strong>Podatki</strong>
        <p><%= simple_format @statement_entry.details %></p>
      </div>
    </div>
  </div>

  <% if @statement_entry.invoice %>
    <div class="col-xs-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Račun</h3>
        </div>
        <div class="panel-body">
          <strong>Račun</strong>
          <p><%= link_to @statement_entry.invoice.receipt_id, admin_invoice_path(@statement_entry.invoice) %></p>
          <strong>Naročnik</strong>
          <p><%= link_to @statement_entry.invoice.customer, admin_customer_path(@statement_entry.invoice.customer) %></p>
          <strong>Izdan</strong>
          <p><%= l @statement_entry.invoice.created_at, format: :simple %></p>
          <strong>Rok</strong>
          <p><%= l @statement_entry.invoice.due_at, format: :simple %></p>
        </div>
      </div>
    </div>
  <% else %>
    <div class="col-xs-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Ročno poveži</h3>
        </div>
        <div class="panel-body">
          <%= form_tag match_admin_statement_entry_path(@statement_entry), method: :post, class: 'form-inline' do %>
            <div class="form-group">
              <%= select_tag :invoice_id, options_for_select(@unpaid_invoices), {class: 'form-control', id: 'invoice_id', placeholder: 'ID računa', prompt: ""} %>
              &nbsp;
              <%= submit_tag "Poveži", class: 'btn btn-primary btn-xs' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% unless @statement_entry.invoice %>
  <h3>Podobni neplačani računi</h3>
  <table class="table rowlinks">
    <thead>
      <tr>
        <th>ID</th>
        <th>Referenca</th>
        <th>Stranka</th>
        <th>Izdan</th>
        <th>Rok</th>
        <th>Plačan</th>
        <th>Znesek</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @statement_entry.matches.each do |invoice| %>
        <tr>
          <td>
            <%= link_to "", admin_invoice_path(invoice) %>
            <%= invoice.receipt_id %></td>
          <td><%= invoice.payment_id %></td>
          <td><%= invoice.customer %></td>
          <td><%= l invoice.created_at, format: :simple %></td>
          <td><%= l invoice.due_at, format: :simple %></td>
          <td>
            <% if invoice.paid? %>
              <%= l invoice.paid_at, format: :simple %></td>
            <% elsif invoice.due? %>
              <span class="label label-danger"><%= invoice.late_days %> dni</span>
            <% end %>
          <td><%= number_to_currency invoice.total %></td>
          <td>
            <%= button_to match_admin_statement_entry_path(@statement_entry, invoice_id: invoice), method: :post, class: 'btn btn-success btn-xs' do %>
              <i class="glyphicon glyphicon-link"></i>
              Združi
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>