config/routes.rb
# frozen_string_literal: true
Web3::Application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users

  scope path_names: { new: 'novo', edit: 'uredi', all: 'vse', search: 'isci' } do
    resources :inquiries, path: 'vprasanja' do
      get :all, on: :collection
      member do
        get :answer_question
        patch :answer
      end
    end
    resources :articles, path: 'clanki', only: [:index, :show] do
      get :search, on: :collection
    end
    resources :issues, path: 'revije', only: [:index, :show]
    resources :orders, path: 'narocila', only: [:new, :create] do
      get :successful, on: :collection, path: 'uspesno'
    end
    resources :copies, path: 'besedila'
    resources :authors, path: 'avtorji', only: [:show]
    resources :news, path: 'pd-vzgojiteljica'
  end

  get '/avtorji-spletne-aplikacije', to: 'pages#authors'
  get '/navodila', to: 'pages#editorial_instructions'

  namespace :admin do
    root to: 'admin#index'
    get :quantities, to: 'admin#quantities'
    get :controls, to: 'admin#controls'
    get :freeriders, to: 'admin#freeriders'
    get :regional, to: 'admin#regional'
    resources :duplicates do
      get :index_customers, on: :collection
      get :index_authors, on: :collection
      post :merge_customers, on: :member
      post :merge_authors, on: :collection
    end
    resources :entities
    resources :postal_costs, only: :index do
      get :calculate, on: :collection
      get :calculate_reward, on: :collection
    end
    resources :institutions, only: :index
    resources :posts
    resources :keywords do
      post :create_simple, on: :collection
    end
    resources :sections
    resources :articles
    resources :authors do
      post :create_simple, on: :collection
    end
    resources :issues do
      member do
        get :edit_cover
        get :edit_document
        patch :cover
        patch :document
      end
    end
    resources :letters do
      get :print, on: :member
    end
    resources :customers do
      post :new_from_order, on: :collection
      get :new_freerider, on: :collection
      post :create_freerider, on: :collection
      get :add_person, on: :member
      get :edit_person, on: :member
      post :create_person, on: :member
      patch :update_person, on: :member
      patch :unsubscribe, on: :member
      post :merge_in, on: :member
      get :email_ingestion, on: :collection
      get :email_ingestion_next, on: :collection
    end
    resources :labels, only: [:index, :show] do
      get :print, on: :collection
    end
    resources :subscribers
    resources :posts
    resources :subscriptions do
      get :patricija, on: :collection
      put :end_now, on: :member
      put :end_by_end_of_year, on: :member
      put :reinstate, on: :member
      post :new_from_order, on: :collection
    end
    resources :plans
    resources :batches
    resources :remarks
    resources :orders, only: [:index, :show]
    resources :order_forms do
      get :download, on: :member
      put :mark_processed, on: :member
      put :process_it, on: :member
    end
    resources :invoices do
      get :wizard, on: :collection
      get :print_wizard, on: :collection
      get :reversed, on: :collection
      get :unpaid, on: :collection
      get :due, on: :collection
      get :print, on: :member
      get :print_all, on: :collection
      get :einvoice, on: :member
      get :eenvelope, on: :member
      get :pdf, on: :member
      post :email, on: :member
      post :email_due, on: :member
      post :build_for_subscription, on: :collection
      post :build_partial_for_subscription, on: :collection
      put :reverse, on: :member
    end
    resources :offers do
      get :wizard, on: :collection
      get :print_wizard, on: :collection
      get :print, on: :member
      get :print_all, on: :collection
      get :pdf, on: :member
      post :create_for_customer, on: :collection
      post :email, on: :member
      post :email_due, on: :member
    end
    resources :bank_statements do
      post :parse, on: :member
    end
    resources :statement_entries, only: [:show] do
      post :match, on: :member
    end
  end

  # Public token route
  get '/:token', to: 'customers#public_show', as: :token
  post '/oddaja_narocilnice', to: 'customers#ingest_order_form', as: :ingest_order_form

  # You can have the root of your site routed with "root"
  # root to: 'copies#show', id: 'pages#index'
  root to: 'pages#index'
end

app/models/customer.rb
# frozen_string_literal: true
class Customer < Entity
  extend DuplicateFinder
  TOKEN_LENGTH = 6

  has_many :subscriptions, through: :subscribers
  has_many :subscribers, dependent: :destroy
  has_many :invoices
  has_many :offers
  has_many :order_forms
  has_one :contact_person, foreign_key: :entity_id, dependent: :destroy
  has_one :billing_person, foreign_key: :entity_id, dependent: :destroy

  before_save :set_einvoice_status
  before_validation :generate_token, on: :create

  scope :einvoiced, -> { where(einvoice: true) }
  scope :not_einvoiced, -> { where(einvoice: false) }
  scope :unsubscribed, -> { where.not(unsubscribed_at: nil) }

  validates :token, presence: true, length: { is: TOKEN_LENGTH }, uniqueness: true

  def global_remarks
    tbl = Remark.arel_table
    query = tbl[:remarkable_id].eq(id).and(tbl[:remarkable_type].eq('Entity'))
    query = query.or(tbl[:remarkable_id].in(subscriber_ids).and(tbl[:remarkable_type].eq('Entity')))
    query = query.or(tbl[:remarkable_id].in(subscriptions.map(&:id)).and(tbl[:remarkable_type].eq('Subscription')))
    query = query.or(tbl[:remarkable_id].in(invoice_ids).and(tbl[:remarkable_type].eq('Invoice')))
    Remark.where(query)
  end

  def quantity
    subscriptions.active.inject(0) { |sum, s| sum += s.quantity }
  end

  def billing_name
    if person?
      name
    else
      billing_person.try(:name)
    end
  end

  def merge_in(other_customer)
    return unless other_customer
    return if id == other_customer.id

    other_customer.subscribers.update_all(customer_id: id)
    other_customer.events.update_all(eventable_id: id)
    other_customer.invoices.update_all(customer_id: id)
    other_customer.remarks.update_all(remarkable_id: id)
    other_customer.reload # Reload to not destroy cached relations, which now belong to other entities.
    other_customer.destroy
  end

  def billing_email
    return billing_person.try(:email) if billing_person && billing_person.email?

    email
  end

  def unsubscribed?
    unsubscribed_at.present?
  end

  def active?
    subscriptions.active.any?
  end

  def self.active
    Subscriber.select(:customer_id)
              .joins(:subscriptions)
              .merge(Subscription.active)
              .includes(:customer)
              .group(:customer_id)
              .map(&:customer)
  end

  def self.active_and_paid
    Subscriber.select(:customer_id)
              .joins(:subscriptions)
              .merge(Subscription.active.paid)
              .includes(:customer)
              .group(:customer_id)
              .map(&:customer)
  end

  def self.active_count
    Subscriber.select(:customer_id)
              .joins(:subscriptions)
              .merge(Subscription.active)
              .group(:customer_id)
              .to_a.size
  end

  def self.paid_count
    Subscriber.select(:customer_id)
              .joins(:subscriptions)
              .merge(Subscription.paid).merge(Subscription.active)
              .group(:customer_id)
              .to_a.size
  end

  def self.new_from_order(order:)
    Customer.transaction do
      customer = new
      customer.title = order.title
      customer.name = order.name
      customer.address = order.address
      customer.post_id = order.post_id
      customer.phone = order.phone
      customer.email = order.email
      customer.vat_id = order.vat_id.gsub(/[^0-9]/, '') if order.vat_id?
      raise FromOrderError, "Can't save customer: #{customer.errors.inspect}" unless customer.save

      customer.remarks.create remark: "Naročnik ustvarjen avtomatsko iz naročila ##{order.id} na spletni strani."

      subscriber = customer.subscribers.new
      subscriber.title = order.title
      subscriber.name = order.name
      subscriber.address = order.address
      subscriber.post_id = order.post_id
      raise FromOrderError, "Can't save subscriber: #{subscriber.errors.inspect}" unless subscriber.save

      if order.comments.present?
        subscriber.remarks.create remark: "Opomba naročnika: \"#{order.comments}\""
      end

      subscription = subscriber.subscriptions.new
      subscription.start = Date.today
      subscription.quantity = order.quantity
      subscription.order_form = order.order_form
      subscription.plan = Plan.latest(order.plan_type) if order.plan_type
      raise FromOrderError, "Can't save subscription: #{subscription.errors.inspect}" unless subscription.save

      order.order_form.customer = customer
      order.order_form.save!

      customer
    end
  end

  def halcom_export
    [
      to_s,
      address,
      post.to_s,
      'SLOVENIJA',
      '',
      account_number,
      bank.name,
      bank.address,
      bank.post.to_s,
      'SLOVENIJA',
      'SI',
      '',
      bank.bic,
      '',
      bank.account_number,
      0,
      '',
      vat_id_formatted.to_s,
      'SI'
    ].map do |el|
      if el.is_a?(String)
        '"' + el + '"'
      else
        el
      end
    end.join(',')
  end

  def to_s
    if title.present?
      title
    elsif name.present?
      name
    else
      "Naročnik ##{id}"
    end
  end

  private

  def set_einvoice_status
    return unless bank

    self.einvoice = bank.einvoice?
  end

  def generate_token
    fund = ('A'..'Z').to_a

    self.token = ''
    TOKEN_LENGTH.times do
      self.token += fund[SecureRandom.random_number(fund.length - 1)]
    end
  end

  class FromOrderError < StandardError; end
end

app/controllers/admin/customers_controller.rb
# frozen_string_literal: true
class Admin::CustomersController < Admin::AdminController
  has_scope :page, default: 1

  def show
    @subscribers = resource.subscribers
    @subscribers_total_count = @subscribers.count

    if params[:filter_subscribers_all]
    elsif params[:filter_subscribers_only_inactive]
      @subscribers = @subscribers.inactive
    elsif params[:filter_subscribers_only_paid]
      @subscribers = @subscribers.paid
    elsif params[:filter_subscribers_only_free]
      @subscribers = @subscribers.free
    else
      @subscribers = @subscribers.active
    end
    @subscribers = @subscribers.to_a.sort_by(&:id)

    @remarks = resource.global_remarks

    respond_with resource
  end

  def new_freerider
    @customer = Customer.new
  end

  def merge
    @customer = Customer.find(params[:id])
  end

  def merge_in
    @customer = Customer.find(params[:id])
    other_customer = Customer.find(params[:other_customer_id])

    @customer.merge_in(other_customer) if @customer && other_customer

    redirect_to admin_customer_path(@customer), notice: "Pridružil #{other_customer.id} k #{@customer.id}"
  end

  def unsubscribe
    customer = Customer.find(params[:id])
    customer.unsubscribed_at = Date.civil(
      params[:customer]["unsubscribed_at(1i)"].to_i,
      params[:customer]["unsubscribed_at(2i)"].to_i,
      params[:customer]["unsubscribed_at(3i)"].to_i
    )
    customer.save!
    redirect_to admin_customer_path(customer)
  end

  def create_freerider
    Customer.transaction do
      @customer = Customer.new
      @subscriber = @customer.subscribers.build
      customer_params = params.require(:customer)
      @customer.title   = @subscriber.title   = customer_params[:title]
      @customer.name    = @subscriber.name    = customer_params[:name]
      @customer.address = @subscriber.address = customer_params[:address]
      @customer.post_id = @subscriber.post_id = customer_params[:post_id]

      @customer.save
      @subscriber.save

      # Subscription
      if customer_params[:subscription]
        @subscription = @subscriber.subscriptions.build
        @subscription.plan = Plan.free
        @subscription.start = DateTime.now
        @subscription.quantity = customer_params[:subscription][:quantity]
        @subscription.reward = customer_params[:subscription][:reward]
        # Type
        type = customer_params[:subscription][:free_type]
        @subscription.end = if type == '1'
                              DateTime.now.end_of_month
                            elsif type == '2'
                              DateTime.now.end_of_year
                            elsif type == '3'
                              1.year.from_now.beginning_of_month
                            elsif type == '4'
          # No end for now.
        end

        if @subscription.save
          redirect_to admin_subscription_path(@subscription)
          return
        end
      end
    end

    render action: :new_freerider
  end

  def new_from_order
    order = Order.find(params[:order_id])
    customer = Customer.new_from_order(order: order)
    order.order_form.processed!(user_id: current_user.id)
    redirect_to admin_customer_path(customer), notice: "Stranka uspešno ustvarjena iz naročila ##{order.id}"
  rescue Customer::FromOrderError => e
    redirect_to admin_order_path(order, error: e.inspect)
  end

  def new
    @all_customers = []
    @customer = Customer.new
    respond_with resource
  end

  def create
    @customer = Customer.create(resource_params)
    if @customer.valid?
      respond_with resource, location: -> { admin_customer_path(@customer) }
    else
      render action: 'new'
    end
  end

  def edit
    @all_customers = Customer.all.select(:id, :name, :title).where.not(id: resource.id).sort_by(&:to_s).map { |c| ["#{c} -- #{c.id}", c.id] }
    respond_with resource, location: -> { admin_customer_path(resource) }
  end

  def update
    resource.update_attributes(resource_params)
    if resource.valid?
      respond_with resource, location: -> { admin_customer_path(@customer) }
    else
      respond_with resource, location: -> { edit_admin_customer_path(@customer) }
    end
  end

  def destroy
    resource.destroy
    respond_with resource, location: -> { admin_entities_path }
  end

  # People

  def add_person
    @entity = case params[:person]
              when 'contact'
                ContactPerson
              when 'billing'
                BillingPerson
    end.new

    @customer = resource
  end

  def edit_person
    @entity = @customer.send("#{params[:person]}_person")
  end

  def update_person
    @entity = Entity.find(params[:person_id])

    if params[:contact_person]
      @entity.update_attributes(params[:contact_person])
    elsif params[:billing_person]
      @entity.update_attributes(params[:billing_person])
    end

    if @entity.valid?
      respond_with resource, location: -> { admin_customer_path(@customer) }
    else
      render 'edit_person'
    end
  end

  def create_person
    @customer = resource
    if params[:contact_person]
      @entity = @customer.build_contact_person(params[:contact_person])
    elsif params[:billing_person]
      @entity = @customer.build_billing_person(params[:billing_person])
    end

    if @entity.valid?
      @entity.save
      @customer.save
      respond_with resource, location: -> { admin_customer_path(@customer) }
    else
      render 'add_person'
    end
  end

  ### EMAIL INGESTION
  def email_ingestion
    query = Customer.arel_table[:email].eq(nil).or(Customer.arel_table[:email].eq(''))
    @customers = Customer.where(query).order(:id)
  end

  def email_ingestion_next
    query = Customer.arel_table[:email].eq(nil).or(Customer.arel_table[:email].eq(''))
    customer = Customer.where(query).order(:id).first
    redirect_to edit_admin_customer_path(customer)
  end

  private

  def resource
    return unless params[:id]
    @customer ||= Customer.find(params[:id])
  end

  def resource_params
    params.require(:customer)
  end

  def set_page_title
    @page_title = 'Naročniki'
  end
end

app/controllers/customers_controller.rb
# frozen_string_literal: true
class CustomersController < Admin::AdminController
  skip_before_filter :authenticate, only: [:public_show, :ingest_order_form]
  layout 'public'

  ###
  ### UNAUTHENTICATED
  ###
  def public_show
    token = params[:token].upcase
    @customer = Customer.find_by(token: token)
    return redirect_to root_path unless @customer

    @invoices = @customer.invoices
    @last_paid_invoice = @invoices.paid.order(created_at: :desc).first
    @subscriptions = @customer.subscriptions.paid.active
    @order_forms = @customer.order_forms.where(year: Date.today.year)
    @order_form ||= @customer.order_forms.new

    @page_title = @customer.to_s
  end

  def ingest_order_form
    return redirect_to root_path unless params[:token].present?

    token = params[:token].upcase
    @customer = Customer.find_by(token: token)
    return redirect_to root_path unless @customer

    if !params[:order_form] || (params[:order_form] && !params[:order_form].any?)
      return redirect_to root_path
    end

    order_form_params = params.require(:order_form).permit(:form_id, :authorizer)
    @order_form = @customer.order_forms.new(order_form_params)
    @order_form.issued_at = DateTime.now
    if @order_form.valid?
      @order_form.save
      redirect_to token_path(@customer.token), notice: 'Vaša naročilnica je bila sprejeta. Najlepša hvala!'
    else
      public_show
      render action: 'public_show'
    end
  end
end

app/views/admin/customers/_customer_info.html.haml
%strong= I18n.t 'attributes.title'
%p= resource.title
%strong= I18n.t 'attributes.address'
%p= resource.address
%strong= I18n.t 'attributes.post'
%p= resource.post
- if resource.city?
  %strong= I18n.t 'attributes.city'
  %p= resource.city
- if resource.phone?
  %strong= I18n.t 'attributes.phone'
  %p= resource.phone
- if resource.email?
  %strong= I18n.t 'attributes.email'
  %p= mail_to resource.email
- if resource.vat_exempt?
  %strong= I18n.t 'attributes.vat_exempt'
- else
  %strong= I18n.t 'attributes.vat_id'
  %p
    - if resource.vat_id? && !resource.vat_id.to_i.zero?
      = resource.vat_id
    - else
      .muted Manjka

app/views/admin/customers/_form.html.haml
:javascript
  $(function() {
    $('#customer_post_id').chosen()
    $('#customer_bank_id').chosen()

    $('#other_customer_id').chosen({
      search_contains: true
    }).on('change', function() {
      var id = $(this).val();
      var name = $(this).find('option:selected').text();
      name = name.substr(0, name.indexOf('--'));
      $('#merge_customers').attr('href', window.location.href.toString().replace('edit', 'merge_in?other_customer_id=' + id)).text('Združi ' + name);
      $('#merge_customers_preview').removeClass('hide').attr('href', '/admin/customers/' + id).text('Poglej ' + name);
    });
  });

.row
  - if @customer.errors.any?
    = @customer.errors.inspect

  .form-inputs.col-xs-8
    = f.input :name
    = f.input :title
    = f.input :address
    = f.association :post
    = f.input :city
    = f.input :phone
    = f.input :email
  .form-inputs.col-xs-4
    - if !@customer.persisted? || (@customer.persisted? && @customer.company?)
      .panel.panel-default
        .panel-heading
          %h3.panel-title Šifre
        .panel-body
          = f.input :registration_number
          = f.input :vat_id
          .checkbox
            %label
              = f.check_box :vat_exempt
              Niso zavezanec za DDV

    .panel.panel-default
      .panel-heading
        %h3.panel-title Napredno
      .panel-body
        .form-group.select.optional.customer_entity_type
          = f.label :entity_type
          = f.select :entity_type, [['', ''], ['Podjetje', Entity::ENTITY_COMPANY], ['Fizična oseba', Entity::ENTITY_PERSON]], {}, class: 'form-control'
        - if !@customer.persisted? || (@customer.persisted? && @customer.company?)
          .checkbox
            %label
              = f.check_box :einvoice
              Sprejemajo e-račune
        .checkbox
          %label
            = f.check_box :manual_delivery
            Pozoj dostava

    - if !@customer.persisted? || (@customer.persisted? && @customer.company?)
      .panel.panel-default
        .panel-heading
          %h3.panel-title Banka
        .panel-body
          = f.association :bank
          = f.input :account_number

    - if @all_customers && @all_customers.any? && @customer.persisted?
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            Pridruži
            .label.label-danger.pull-right Previdno!
        .panel-body
          .form-group.select.optional.customer_entity_type
            = select_tag :other_customer_id, options_for_select(@all_customers), {class: 'form-control', id: 'other_customer_id', placeholder: 'ID stranke', prompt: ""}
            %br
            %br
            = link_to "Pridruži", merge_in_admin_customer_path(@customer), :"data-method" => "post", id: 'merge_customers', class: 'btn btn-danger btn-sm'
            %br
            %small
              = link_to "Poglej", "", id: 'merge_customers_preview', class: 'hide'

.form-actions
  %hr
  = f.button :submit

app/views/admin/customers/_person_form.html.haml
:javascript
  $(function() {
    $('#entity_name').focus()
  });

.row
  .form-inputs.col-xs-8
    = f.input :name
    = f.input :title
    = f.input :phone
    = f.input :email

.form-actions
  %hr
  = f.button :submit

app/views/admin/customers/add_person.html.haml
%h1 Nova oseba

= simple_form_for [:admin, @entity], url: create_person_admin_customer_path(@customer) do |f|
  = f.error_notification
  = render "person_form", f: f

app/views/admin/customers/edit.html.haml
%h1= @customer

= simple_form_for [:admin, @customer] do |f|
  = f.error_notification
  = render "form", f: f

app/views/admin/customers/edit_person.html.haml
%h1 Uredi osebo

= simple_form_for @entity, url: update_person_admin_customer_path(@customer, person_id: @entity.id) do |f|
  = f.error_notification
  = render "person_form", f: f

app/views/admin/customers/index.html.haml
%h1 Partnerji
- generate_table collection, [:id, :title, :name], [:show], :admin
= paginate collection

app/views/admin/customers/show.html.haml
%h1
  = @customer
  - if @customer.unsubscribed_at
    %small.label.label-danger
      Odpoved
      =l @customer.unsubscribed_at, format: '%d.%m.%Y'

.admin_actions
  = link_to admin_customer_path(@customer), class: 'btn btn-danger', method: :delete, data: { confirm: 'Ta gumb je samo za Miha! :) Če nisi Miha, prekliči operacijo.' } do
    %i.glyphicon.glyphicon-trash
    Izbriši
  = link_to edit_admin_customer_path(@customer), class: 'btn btn-default' do
    %i.glyphicon.glyphicon-edit
    Uredi

.row
  .col-xs-6
    .details.panel.panel-default
      .panel-body
        = render "fields", resource: @customer
        - if @customer.token?
          %hr
          %strong Javni dostop
          %p= link_to token_url(@customer.token), token_url(@customer.token)

        - if @customer.company?
          %hr
          %h4
            Kontaktna oseba
            - if @customer.contact_person
              = link_to edit_person_admin_customer_path(@customer, person: :contact), class: 'btn btn-xs btn-default' do
                %i.glyphicon.glyphicon-user
                Uredi
            - else
              = link_to add_person_admin_customer_path(@customer, person: :contact), class: 'btn btn-xs btn-default' do
                %i.glyphicon.glyphicon-user
                Dodaj

          - if @customer.contact_person
            = render "admin/people/fields", resource: @customer.contact_person

          %hr
          %h4
            Plačilni kontakt
            - if @customer.billing_person
              = link_to edit_person_admin_customer_path(@customer, person: :billing), class: 'btn btn-xs btn-default' do
                %i.glyphicon.glyphicon-user
                Uredi
            - else
              = link_to add_person_admin_customer_path(@customer, person: :billing), class: 'btn btn-xs btn-default' do
                %i.glyphicon.glyphicon-user
                Dodaj
          - if @customer.billing_person
            = render "admin/people/fields", resource: @customer.billing_person
        - if @customer.flags && @customer.flags.any?
          %hr
          %h4
            Nastavitve
          %p
            %code= @customer.flags.to_sentence

        - if @customer.events.any?
          %hr
          = render 'events/events', events: @customer.events

  .col-xs-6
    = render "admin/remarks/form", resource: @customer, remarks: @remarks

    - unless @customer.unsubscribed?
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            Odpoved naročnine
        .panel-body
          = form_tag unsubscribe_admin_customer_path(@customer), method: :patch do
            = date_select :customer, :unsubscribed_at
            = submit_tag

.panel.panel-default
  .panel-heading
    %h3.panel-title
      Prejemniki

      %small
        = conditional_filtering_link("Aktivni", default: true, url: admin_customer_path(@customer))
        = conditional_filtering_link("Neaktivni", param: :filter_subscribers_only_inactive)
        = conditional_filtering_link("Plačljivi", param: :filter_subscribers_only_paid)
        = conditional_filtering_link("Brezplačni", param: :filter_subscribers_only_free)
        = conditional_filtering_link("Vsi", param: :filter_subscribers_all)

      = link_to new_admin_subscriber_path(customer_id: @customer.id), class: 'btn btn-default btn-xs pull-right' do
        %i.glyphicon.glyphicon-plus
        Ustvari
      = link_to new_admin_subscriber_path(customer_id: @customer.id, customer: true), class: 'btn btn-default btn-xs pull-right' do
        %i.glyphicon.glyphicon-plus
        Ustvari kot kopijo naročnika

  %table.table.rowlinks
    %thead
      %tr
        %th ID
        %th Naziv
        %th Naslov
        %th Pošta
        %th Količina
        %th Naročnina
    %tbody
      - @subscribers.each do |s|
        %tr
          %td
            = link_to "", admin_subscriber_path(s)
            = s.id
          %td= render "shared/subscriber_name_and_title", subscriber: s
          %td= s.address
          %td= s.post
          %td= s.subscriptions.active.sum(:quantity)
          %td.subscriptions
            - s.subscriptions.active.each do |subscription|
              .subscription
                = subscription.plan
                %small.text-muted== (#{subscription.id})
                %br
                - if subscription.start?
                  %small.label.label-success= l subscription.start
                - if subscription.end?
                  %small.label.label-danger= l subscription.end
                - if subscription.is_reward?
                  %small.label.label-warning
                    %i.glyphicon.glyphicon-gift
    - if @subscribers.count < @subscribers_total_count
      %tfoot
        %tr
          %td{colspan: 99}
            %small.muted
              = @subscribers_total_count - @subscribers.count
              prejemnikov je skritih zaradi filtriranja
              &mdash;
              = link_to "Prikaži vse", admin_customer_path(@customer, filter_subscribers_all: true)

- if @customer.invoices.any?
  .panel.panel-default
    .panel-heading
      %h3.panel-title Izdani računi

    %table.table.rowlinks
      %thead
        %tr
          %th ID
          %th Številka
          %th Izdan
          %th Rok
          %th Znesek
      %tbody
        - @customer.invoices.order(year: :desc, reference_number: :desc).each do |invoice|
          %tr
            %td
              = link_to "", admin_invoice_path(invoice)
              = invoice.receipt_id
            %td= invoice.issues.distinct.join(', ')
            %td= l invoice.created_at, format: :simple
            %td= l invoice.due_at, format: :simple
            %td
              - if invoice.paid?
                .label.label-success
                  = number_to_currency invoice.total
              - elsif invoice.due?
                .label.label-danger
                  = number_to_currency invoice.total
              - elsif invoice.reversed?
                .label.label-primary
                  = number_to_currency invoice.total
              - else
                = number_to_currency invoice.total

.panel.panel-default
  .panel-heading
    %h3.panel-title
      Izdane ponudbe

      = link_to create_for_customer_admin_offers_path(customer_id: @customer.id), class: 'btn btn-default btn-xs pull-right', :"data-method" => :post do
        %i.glyphicon.glyphicon-plus
        Ustvari

  - if @customer.offers.any?
    %table.table.rowlinks
      %thead
        %tr
          %th Ref. št.
          %th Izdana
          %th Znesek
      %tbody
        - @customer.offers.order(year: :desc, reference_number: :desc).each do |offer|
          %tr
            %td
              = link_to "", admin_offer_path(offer)
              = offer.reference_number
            %td= l offer.created_at, format: :simple
            %td= number_to_currency offer.total

- if @customer.order_forms.any?
  .panel.panel-default
    .panel-heading
      %h3.panel-title Naročilnice

    %table.table.rowlinks
      %thead
        %tr
          %th Št. Nar.
          %th Podpisnik
          %th Pričetek
          %th Konec
      %tbody
        - @customer.order_forms.order(year: :desc, start: :desc).each do |order_form|
          %tr
            %td
              = link_to "", admin_order_form_path(order_form)
              = order_form.form_id
            %td= order_form.authorizer
            %td
              - if order_form.start
                = l order_form.start, format: :simple
              - else
                &mdash;
            %td
              - if order_form.end
                = l order_form.end, format: :simple
              - else
                &mdash;