config/routes.rb
# frozen_string_literal: true
Web3::Application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users

  scope path_names: { new: 'novo', edit: 'uredi', all: 'vse', search: 'isci' } do
    resources :inquiries, path: 'vprasanja' do
      get :all, on: :collection
      member do
        get :answer_question
        patch :answer
      end
    end
    resources :articles, path: 'clanki', only: [:index, :show] do
      get :search, on: :collection
    end
    resources :issues, path: 'revije', only: [:index, :show]
    resources :orders, path: 'narocila', only: [:new, :create] do
      get :successful, on: :collection, path: 'uspesno'
    end
    resources :copies, path: 'besedila'
    resources :authors, path: 'avtorji', only: [:show]
    resources :news, path: 'pd-vzgojiteljica'
  end

  get '/avtorji-spletne-aplikacije', to: 'pages#authors'
  get '/navodila', to: 'pages#editorial_instructions'

  namespace :admin do
    root to: 'admin#index'
    get :quantities, to: 'admin#quantities'
    get :controls, to: 'admin#controls'
    get :freeriders, to: 'admin#freeriders'
    get :regional, to: 'admin#regional'
    resources :duplicates do
      get :index_customers, on: :collection
      get :index_authors, on: :collection
      post :merge_customers, on: :member
      post :merge_authors, on: :collection
    end
    resources :entities
    resources :postal_costs, only: :index do
      get :calculate, on: :collection
      get :calculate_reward, on: :collection
    end
    resources :institutions, only: :index
    resources :posts
    resources :keywords do
      post :create_simple, on: :collection
    end
    resources :sections
    resources :articles
    resources :authors do
      post :create_simple, on: :collection
    end
    resources :issues do
      member do
        get :edit_cover
        get :edit_document
        patch :cover
        patch :document
      end
    end
    resources :letters do
      get :print, on: :member
    end
    resources :customers do
      post :new_from_order, on: :collection
      get :new_freerider, on: :collection
      post :create_freerider, on: :collection
      get :add_person, on: :member
      get :edit_person, on: :member
      post :create_person, on: :member
      patch :update_person, on: :member
      patch :unsubscribe, on: :member
      post :merge_in, on: :member
      get :email_ingestion, on: :collection
      get :email_ingestion_next, on: :collection
    end
    resources :labels, only: [:index, :show] do
      get :print, on: :collection
    end
    resources :subscribers
    resources :posts
    resources :subscriptions do
      get :patricija, on: :collection
      put :end_now, on: :member
      put :end_by_end_of_year, on: :member
      put :reinstate, on: :member
      post :new_from_order, on: :collection
    end
    resources :plans
    resources :batches
    resources :remarks
    resources :orders, only: [:index, :show]
    resources :order_forms do
      get :download, on: :member
      put :mark_processed, on: :member
      put :process_it, on: :member
    end
    resources :invoices do
      get :wizard, on: :collection
      get :print_wizard, on: :collection
      get :reversed, on: :collection
      get :unpaid, on: :collection
      get :due, on: :collection
      get :print, on: :member
      get :print_all, on: :collection
      get :einvoice, on: :member
      get :eenvelope, on: :member
      get :pdf, on: :member
      post :email, on: :member
      post :email_due, on: :member
      post :build_for_subscription, on: :collection
      post :build_partial_for_subscription, on: :collection
      put :reverse, on: :member
    end
    resources :offers do
      get :wizard, on: :collection
      get :print_wizard, on: :collection
      get :print, on: :member
      get :print_all, on: :collection
      get :pdf, on: :member
      post :create_for_customer, on: :collection
      post :email, on: :member
      post :email_due, on: :member
    end
    resources :bank_statements do
      post :parse, on: :member
    end
    resources :statement_entries, only: [:show] do
      post :match, on: :member
    end
  end

  # Public token route
  get '/:token', to: 'customers#public_show', as: :token
  post '/oddaja_narocilnice', to: 'customers#ingest_order_form', as: :ingest_order_form

  # You can have the root of your site routed with "root"
  # root to: 'copies#show', id: 'pages#index'
  root to: 'pages#index'
end

app/models/order.rb
# frozen_string_literal: true
class Order < ActiveRecord::Base
  attr_accessor :desire

  validates_presence_of :name, :address, :post_id
  validates :quantity, presence: true, numericality: { greater_than: 0, only_integer: true }
  validates :email, presence: true, email: true
  validates :plan_type, presence: true, inclusion: { in: [1, 6] }
  validate  :validate_plan_type

  belongs_to :post
  has_many :subscriptions # TODO: remove after migration
  has_many :remarks, as: :remarkable, dependent: :destroy
  has_many :events, as: :eventable, dependent: :destroy
  has_one :order_form

  scope :processed, -> { where(processed: true) }
  scope :not_processed, -> { where(processed: false) }

  after_create :create_order_form

  def order_id
    "#{created_at.strftime('%Y')}-#{id}"
  end

  def plan_type_string
    if plan_type == 1
      'Letna naročnina'
    elsif plan_type == 6
      'Plačilo za vsako posamezno številko'
    end
  end

  def to_s
    base = "Naročilo ##{id}"
    if title.present?
      return "#{base} (#{title})"
    elsif name.present?
      return "#{base} (#{name})"
    end

    base
  end

  private

  def validate_plan_type
    return unless quantity? || plan_type?

    if quantity == 1 && plan_type == 6
      errors.add :plan_type, 'za plačevanje po posamezni številki mora biti naročena količina vsaj 2'
    end
  end

  def create_order_form
    order_form = build_order_form
    order_form.issued_at = created_at
    order_form.form_id = "Naročilo ##{id}"
    order_form.save
  end
end

app/models/order_form.rb
# frozen_string_literal: true
class OrderForm < ActiveRecord::Base
  has_attached_file :document,
                    whiny: false,
                    storage: :s3,
                    bucket: AWS_S3['bucket'],
                    s3_credentials: {
                      access_key_id: AWS_S3['access_key_id'],
                      secret_access_key: AWS_S3['secret_access_key']
                    },
                    s3_permissions: {
                      original: :private,
                      preview: :public_read
                    },
                    s3_storage_class: :reduced_redundancy,
                    path: '/order_forms/:year/:id_:basename_:style.:extension',
                    styles: { preview: { geometry: '150x150>', format: :jpg } }

  validates_attachment_content_type :document, content_type: [/\Aimage\/.*\Z/, 'application/pdf']

  validates_presence_of :form_id

  Paperclip.interpolates :year do |attachment, _style|
    # TODO: remove this after 2015 is done to remove ambiguity
    date = attachment.instance.issued_at || attachment.instance.created_at
    date.year.to_s
  end

  belongs_to :customer
  belongs_to :order
  belongs_to :offer
  has_many :subscriptions
  has_many :remarks, as: :remarkable, dependent: :destroy
  has_many :events, as: :eventable, dependent: :destroy

  scope :not_processed, -> { where(processed_at: nil) }
  scope :active, -> { where(arel_table[:start].lteq(Date.today).and(arel_table[:end].eq(nil).or(arel_table[:end].gteq(Date.today)))) }
  scope :inactive, -> { where(arel_table[:end].not_eq(nil).and(arel_table[:end].lteq(Date.today).or(arel_table[:start].gteq(Date.today)))) }

  before_save :set_year, if: :issued_at?

  def to_s
    form_id
  end

  def label_description
    parts = [form_id]
    parts.push "(#{issued_at})" if issued_at
    if order
      if order.title.present?
        parts.push order.title
      else
        parts.push order.name
      end
    elsif customer
      parts.push customer.to_s
    end

    parts.join(' - ')
  end

  def self.years
    distinct(:year).order(year: :desc).pluck(:year).compact
  end

  def able_to_process_attach?
    return unless customer
    subs = customer.subscriptions.active.paid
    return unless subs.any?

    subs.none?(&:order_form)
  end

  def process_attach!(user_id: nil)
    return unless able_to_process_attach?

    OrderForm.transaction do
      customer.subscriptions.active.paid.each do |subscription|
        next if subscription.order_form
        subscription.order_form = self
        subscription.save!
      end

      processed!(user_id: user_id)
    end
  end

  def able_to_process_renew?
    return unless customer
    subs = customer.subscriptions.active.paid
    return unless subs.any?

    return unless subs.none? { |subscription| subscription.order_form === self }
    subs.any?(&:order_form)
  end

  def process_renew!(user_id: nil)
    return unless able_to_process_renew?

    OrderForm.transaction do
      customer.subscribers.each do |subscriber|
        subs = subscriber.subscriptions.active.paid
        total_quantity = subs.sum(:quantity)

        next unless subs.any?

        # End all existing subscriptions.
        subs.each do |subscription|
          subscription.end = 1.year.ago.end_of_year
          subscription.events.create(event: :subscription_auto_canceled, details: id)
          subscription.remarks.create(remark: "Naročnina avtomatsko prekinjena zaradi procesiranja naročilnice ID #{id} (#{form_id})")
          subscription.save!
        end

        # Create a new subscription with combined quantity.
        new_sub = subs.first.dup
        new_sub.start = start || issued_at
        new_sub.end = self.end if end?
        new_sub.quantity = total_quantity
        new_sub.order_form = self
        new_sub.save!

        new_sub.events.create(event: :subscription_from_order_form, details: id)
        new_sub.remarks.create(remark: "Nova naročnina avtomatsko ustvarjena zaradi procesiranja naročilnice ID #{id} (#{form_id})")
        processed!(user_id: user_id)

        return new_sub
      end
    end
  end

  def processed!(user_id: nil)
    OrderForm.transaction do
      self.processed_at = DateTime.now
      save!

      if order && !order.processed?
        order.processed = true
        order.save!
      end

      events.create event: :order_form_processed, user_id: user_id
    end
  end

  def processed?
    processed_at && processed_at <= DateTime.now
  end

  def active?
    start && start <= DateTime.now && (!self.end || (self.end && self.end >= DateTime.now))
  end

  private

  def set_year
    self.year = issued_at.year
  end
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true
class Admin::OrdersController < Admin::AdminController
  def index
    @orders = Order.all.order(created_at: :desc).page(params[:page]).per(20)
    return if params[:filter_all]

    @orders = @orders.not_processed
  end

  def show
    resource
  end

  def destroy
    order = Order.find(params[:id])
    if order.destroy
      redirect_to admin_orders_path, notice: 'Naročilo uspešno izbrisano'
    end
  end

  private

  def resource
    @order ||= Order.find_by(id: params[:id])
  end

  def set_page_title
    @page_title = 'Naročila'
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true
class OrdersController < ApplicationController
  skip_before_filter :authenticate, only: [:new, :create, :successful]

  def new
    @order = Order.new
    respond_with @order
  end

  def create
    # Honeypotz
    if params[:order][:desire] && params[:order][:desire].present?
      render text: 'Thank you for your order!'
      return
    end

    @order = Order.new params[:order]
    @order.ip = request.remote_ip
    if @order.save
      AdminMailer.delay.new_order(@order.id)
      Mailer.delay.order_submitted(@order.id)
      redirect_to successful_orders_path
    else
      render action: :new
    end
  end

  private

  def resource
    return unless params[:id]
    @order ||= Order.find(params[:id])
  end
end

app/views/admin/orders/_fields.html.erb
<strong>Naziv:</strong>
<p>
  <%= order.title %>
</p>
<strong>Ime in priimek:</strong>
<p>
  <%= order.name %>
</p>
<strong>Naslov:</strong>
<p>
  <%= order.address %>
  <br>
  <%= order.post %>
</p>
<strong>Email:</strong>
<p>
  <%= order.email %>
</p>
<% if order.vat_id? %>
  <strong>ID št. za DDV:</strong>
  <p>
    <%= order.vat_id %>
  </p>
<% end %>
<% if order.phone? %>
  <strong>Telefon:</strong>
  <p>
    <%= order.phone %>
  </p>
<% end %>
<strong>Količina:</strong>
<p><%= order.quantity %> izvod(ov)</p>
<strong>Plan plačila:</strong>
<p><%= order.plan_type_string %></p>
<% if order.comments.present? %>
  <hr>
  <strong>Opombe:</strong>
  <p><%= order.comments %></p>
<% end %>

app/views/admin/orders/index.html.erb
<h2>
  Naročila
  <small>
    <%= conditional_filtering_link "Neobdelana", default: true, route: admin_orders_path %>
    |
    <%= conditional_filtering_link "Vsa naročila", param: :filter_all %>
  </small>
</h2>

<%= paginate @orders %>

<table class="table rowlinks">
  <thead>
    <tr>
      <th>Naziv</th>
      <th>Naslov</th>
      <th>Pošta</th>
      <th>Kol.</th>
      <th>Plan</th>
      <th>Ustvarjeno</th>
      <th>Procesirano</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td>
          <%= link_to "", admin_order_path(order) %>
          <% if order.title? %>
            <%= order.title %>
            <% if order.name? %>
              <br>
              <span class="muted"><%= order.name %></span>
            <% end %>
          <% else %>
            <%= order.name %>
          <% end %>
        </td>
        <td><%= order.address %></td>
        <td><%= order.post %></td>
        <td><%= order.quantity %></td>
        <td>
          <% if order.plan_type == 1 %>
            let
          <% elsif order.plan_type == 6 %>
            št
          <% end %>
        </td>
        <td><%=l order.created_at %></td>
        <td>
          <% if order.processed? %>
            &#10003;
          <% else %>
            &#10007;
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @orders %>

app/views/admin/orders/show.html.erb
<script type="text/javascript">
  $(function() {
    $('#subscriber_id').chosen({
      search_contains: true
    });
  });
</script>

<% if params[:error] %><%= debug params[:error] %><% end %>

<h1>
  Naročilo #<%= @order.id %>
  <small class="muted">iz spletne strani</small>
  <% if @order.processed? %>
    <small class="label label-success pull-right">Sprocesirano</small>
  <% else %>
    <small class="label label-danger pull-right">Odprto</small>
  <% end %>
</h1>

<div class="row">
  <div class="col-xs-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'admin/orders/fields', order: @order %>
      </div>
    </div>
  </div>
  <div class="col-xs-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if @order.order_form %>
          <strong>Naročilnica:</strong>
          <p>
            <%= link_to @order.order_form, admin_order_form_path(@order.order_form) %>
          </p>
          <hr>
        <% end %>
        <strong>Ustvarjeno:</strong>
        <p>
          <%= l @order.created_at %>
        </p>
        <% unless @order.created_at == @order.updated_at %>
          <strong>Osveženo:</strong>
          <p>
            <%= l @order.updated_at %>
          </p>
        <% end %>
        <% if @order.ip? %>
          <p><strong>IP:</strong> <%= @order.ip %></p>
        <% end %>
        <% if @order.events.any? %>
          <hr>
          <strong>Dogodki:</strong>
          <%= render 'events/events', events: @order.events %>
        <% end %>
      </div>
    </div>
  </div>
</div>