config/routes.rb
# frozen_string_literal: true
Web3::Application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users

  scope path_names: { new: 'novo', edit: 'uredi', all: 'vse', search: 'isci' } do
    resources :inquiries, path: 'vprasanja' do
      get :all, on: :collection
      member do
        get :answer_question
        patch :answer
      end
    end
    resources :articles, path: 'clanki', only: [:index, :show] do
      get :search, on: :collection
    end
    resources :issues, path: 'revije', only: [:index, :show]
    resources :orders, path: 'narocila', only: [:new, :create] do
      get :successful, on: :collection, path: 'uspesno'
    end
    resources :copies, path: 'besedila'
    resources :authors, path: 'avtorji', only: [:show]
    resources :news, path: 'pd-vzgojiteljica'
  end

  get '/avtorji-spletne-aplikacije', to: 'pages#authors'
  get '/navodila', to: 'pages#editorial_instructions'

  namespace :admin do
    root to: 'admin#index'
    get :quantities, to: 'admin#quantities'
    get :controls, to: 'admin#controls'
    get :freeriders, to: 'admin#freeriders'
    get :regional, to: 'admin#regional'
    resources :duplicates do
      get :index_customers, on: :collection
      get :index_authors, on: :collection
      post :merge_customers, on: :member
      post :merge_authors, on: :collection
    end
    resources :entities
    resources :postal_costs, only: :index do
      get :calculate, on: :collection
      get :calculate_reward, on: :collection
    end
    resources :institutions, only: :index
    resources :posts
    resources :keywords do
      post :create_simple, on: :collection
    end
    resources :sections
    resources :articles
    resources :authors do
      post :create_simple, on: :collection
    end
    resources :issues do
      member do
        get :edit_cover
        get :edit_document
        patch :cover
        patch :document
      end
    end
    resources :letters do
      get :print, on: :member
    end
    resources :customers do
      post :new_from_order, on: :collection
      get :new_freerider, on: :collection
      post :create_freerider, on: :collection
      get :add_person, on: :member
      get :edit_person, on: :member
      post :create_person, on: :member
      patch :update_person, on: :member
      patch :unsubscribe, on: :member
      post :merge_in, on: :member
      get :email_ingestion, on: :collection
      get :email_ingestion_next, on: :collection
    end
    resources :labels, only: [:index, :show] do
      get :print, on: :collection
    end
    resources :subscribers
    resources :posts
    resources :subscriptions do
      get :patricija, on: :collection
      put :end_now, on: :member
      put :end_by_end_of_year, on: :member
      put :reinstate, on: :member
      post :new_from_order, on: :collection
    end
    resources :plans
    resources :batches
    resources :remarks
    resources :orders, only: [:index, :show]
    resources :order_forms do
      get :download, on: :member
      put :mark_processed, on: :member
      put :process_it, on: :member
    end
    resources :invoices do
      get :wizard, on: :collection
      get :print_wizard, on: :collection
      get :reversed, on: :collection
      get :unpaid, on: :collection
      get :due, on: :collection
      get :print, on: :member
      get :print_all, on: :collection
      get :einvoice, on: :member
      get :eenvelope, on: :member
      get :pdf, on: :member
      post :email, on: :member
      post :email_due, on: :member
      post :build_for_subscription, on: :collection
      post :build_partial_for_subscription, on: :collection
      put :reverse, on: :member
    end
    resources :offers do
      get :wizard, on: :collection
      get :print_wizard, on: :collection
      get :print, on: :member
      get :print_all, on: :collection
      get :pdf, on: :member
      post :create_for_customer, on: :collection
      post :email, on: :member
      post :email_due, on: :member
    end
    resources :bank_statements do
      post :parse, on: :member
    end
    resources :statement_entries, only: [:show] do
      post :match, on: :member
    end
  end

  # Public token route
  get '/:token', to: 'customers#public_show', as: :token
  post '/oddaja_narocilnice', to: 'customers#ingest_order_form', as: :ingest_order_form

  # You can have the root of your site routed with "root"
  # root to: 'copies#show', id: 'pages#index'
  root to: 'pages#index'
end

app/models/invoice.rb
# frozen_string_literal: true
class Invoice < Receipt
  has_many :statement_entries

  validates :payment_id, presence: true, uniqueness: true

  before_validation :generate_payment_id, unless: :payment_id?
  before_save :fill_period, on: :create

  scope :not_due, -> { where("receipts.due_at > '#{DateTime.now}'") }
  scope :due, -> { where("receipts.due_at < '#{DateTime.now}'").where(reversed_at: nil) }
  scope :unpaid, -> { where(paid_at: nil) }
  scope :paid,   -> { where.not(paid_at: nil) }
  scope :unreversed, -> { where(reversed_at: nil) }
  scope :reversed,   -> { where.not(reversed_at: nil) }

  def balance
    paid_amount - total
  end

  def paid?
    paid_at? && paid_amount >= total
  end

  def reversed?
    reversed_at?
  end

  def due?
    return false if reversed?
    due_at <= DateTime.now
  end

  def late_days
    (Date.today - due_at.to_date).floor
  end

  def generate_payment_id
    return unless customer_id?
    self.payment_id ||= "#{customer_id}-#{receipt_id}"
  end

  def einvoice_path
    file_path('xml')
  end

  def eenvelope_path
    file_path('xml', 'env_')
  end

  def store_all_on_s3
    super
    store_einvoice
    return unless customer.einvoice?
    store_eenvelope
  end

  def einvoice_exists_on_s3?
    exists_on_s3?(einvoice_path)
  end

  def eenvelope_exists_on_s3?
    exists_on_s3?(eenvelope_path)
  end

  def store_einvoice
    store_to_s3(einvoice_path, einvoice_xml)
    einvoice_path
  end

  def store_eenvelope
    store_to_s3(eenvelope_path, eenvelope_xml)
    eenvelope_path
  end

  def einvoice_url
    s3_url(einvoice_path)
  end

  def eenvelope_url
    s3_url(eenvelope_path)
  end

  def einvoice
    EInvoice.new(invoice: self)
  end

  def einvoice_xml
    [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<IzdaniRacunEnostavni xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xds="http://uri.etsi.org/01903/v1.1.1#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.gzs.si/e-poslovanje/sheme/eSLOG_1-6_EnostavniRacun.xsd">',
      einvoice.generate,
      '</IzdaniRacunEnostavni>'
    ].join("\n")
  end

  def eenvelope
    EEnvelope.new(invoice: self)
  end

  def eenvelope_xml
    [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<package xmlns="hal:icl:01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" pkg_type="einvoice">',
      eenvelope.generate,
      '</package>'
    ].join("\n")
  end

  def payment_id_full
    "SI00#{payment_id}"
  end

  def parse_iban_from_bank_data
    return unless bank_data
    return unless iban_string = bank_data.split("\n").first
    return unless iban_string.present?
    return unless IBANTools::IBAN.valid?(iban_string)
    iban_string
  end

  def to_s
    s = "Račun #{receipt_id} "
    if paid?
      return s + '(plačan)'
    else
      return s + '(neplačan)'
    end
  end

  def fill_period
    return if period_from || period_to
    
    self.period_from = Date.today
    self.period_to = Date.today
  end
end

app/controllers/admin/invoices_controller.rb
# frozen_string_literal: true
class Admin::InvoicesController < Admin::ReceiptsController
  def index
    @years = Invoice.years
    @year_now = DateTime.now.year
    @all_invoices = Invoice.select(:id, :receipt_id).order(year: :desc, reference_number: :desc).map { |i| [i.receipt_id, i.receipt_id] }

    @invoices = collection
    if params[:filter_year]
      @invoices = @invoices.where(year: params[:filter_year])
    elsif params[:filter_year_all]
    else
      @invoices = @invoices.where(year: @year_now)
    end
    respond_with collection
  end

  def unpaid
    @years = Invoice.years
    @invoices = collection.unpaid.unreversed
    if params[:year]
      @invoices = @invoices.where(year: params[:year])
    elsif params[:all]
    else
      @invoices = @invoices.where(year: DateTime.now.year)
    end
    respond_with collection
  end

  def due
    @years = Invoice.years
    @invoices = collection.due.unpaid.unreversed
    if params[:year]
      @invoices = @invoices.where(year: params[:year])
    elsif params[:all]
    else
      @invoices = @invoices.where(year: DateTime.now.year)
    end
    respond_with collection
  end

  def reversed
    @years = Invoice.years
    @invoices = collection.reversed
    if params[:year]
      @invoices = @invoices.where(year: params[:year])
    elsif params[:all]
    else
      @invoices = @invoices.where(year: DateTime.now.year)
    end
    respond_with collection
  end

  def reverse
    @invoice = resource
    @invoice.reversed_at = Time.now
    @invoice.reverse_reason = params.require(:invoice).delete(:reverse_reason)
    @invoice.save

    respond_with resource, location: -> { admin_invoice_path(@invoice) }
  end

  def wizard
    @wizard = ReceiptWizard.new(wizard_params)
    @last = Invoice.select(:reference_number)
                   .where(year: Date.today.year)
                   .order(year: :desc, reference_number: :desc)
                   .first.try(:reference_number) || 0
  end

  def print_wizard
    @gte = Invoice.select(:reference_number).order(:year, :reference_number).first.try(:reference_number)
    @lte = Invoice.select(:reference_number).order(year: :desc, reference_number: :desc).first.try(:reference_number)
  end

  def create
    ReceiptWizardWorker.perform_async(wizard_params)

    redirect_to admin_invoices_path, notice: 'Ustvarjam račune'
  end

  def email
    customer = resource.customer

    unless customer.billing_email.present?
      return redirect_to(admin_invoice_path, notice: 'Ni plačilnega kontakta ali pa ta nima nastavljenega e-maila')
    end

    Mailer.delay.invoice_to_customer(resource.id)
    redirect_to admin_invoice_path, notice: "Račun poslan na #{customer.billing_email}"
  end

  def email_due
    unless resource.due?
      return redirect_to(admin_invoice_path, notice: 'Račun še ni zapadel, zato ne bomo poslali opomina.')
    end

    customer = resource.customer

    unless customer.billing_email.present?
      return redirect_to(admin_invoice_path, notice: 'Ni plačilnega kontakta ali pa ta nima nastavljenega e-maila')
    end

    Mailer.delay.invoice_due_to_customer(resource.id)
    redirect_to :back, notice: "Opomin poslan na #{customer.billing_email}"
  end

  def build_for_subscription
    subscription = Subscription.find(params[:subscription_id])

    wizard = ReceiptWizard.new(wizard_params)
    unless subscription.plan.yearly?
      wizard.issue_id = Issue.order(published_at: :desc).first.id
    end
    @invoice = wizard.build_receipt_for_subscription subscription

    return render text: @invoice.errors.inspect unless @invoice.save

    redirect_to admin_invoice_path(@invoice)
  end

  def build_partial_for_subscription
    subscription = Subscription.find(params[:subscription_id])
    issues_left = params[:issues_left]

    unless issues_left.present?
      return redirect_to :back, notice: 'Please provide issues left'
    end

    wizard = ReceiptWizard.new(wizard_params)
    @invoice = wizard.build_partial_receipt_for_subscription(subscription, issues_left)

    return render text: @invoice.errors.inspect unless @invoice.save

    render json: { receipt_id: @invoice.id, redirect: admin_invoice_path(@invoice) }
  end

  def einvoice
    @einvoice = EInvoice.new(invoice: resource).generate
    respond_to do |format|
      format.xml { render layout: 'einvoice' }
    end
  end

  def eenvelope
    @eenvelope = EEnvelope.new(invoice: resource).generate
    respond_to do |format|
      format.xml { render layout: 'eenvelope' }
    end
  end

  def print_all
    @invoices = Invoice.all

    if lte = params[:lte]
      @invoices = @invoices.where("year = #{params[:year]} AND reference_number <= #{lte}")
    end
    if gte = params[:gte]
      @invoices = @invoices.where("year = #{params[:year]} AND reference_number >= #{gte}")
    end
    @invoices = @invoices.order(:year, :reference_number)

    unless params[:include_einvoiced].present?
      @invoices = @invoices.reject { |i| i.customer.einvoice? }
    end

    render layout: 'print'
  end

  private

  def collection
    @invoices ||= Invoice.order(year: :desc, reference_number: :desc).page(params[:page]).per(50)
  end

  def resource
    return unless params[:id]
    @invoice = Invoice.find_by(receipt_id: params[:id])
  end

  def set_page_title
    @page_title = 'Računi'
  end

  def wizard_params
    return @wizard_params if @wizard_params
    @wizard_params = params[:receipt_wizard] || {}
    @wizard_params.merge!(type: :invoice)
  end
end

app/views/admin/invoices/_print_with_vat.html.erb
<% invoice ||= @invoice %>
<div class="receipt">
  <header>
    <%= image_tag "pozoj_logo-100w.png" %>
    <p>
      <strong><%= Entity.supra %></strong>
    </p>
    <p>
      <%= Entity.supra.address %>
      <br>
      <%= Entity.supra.post %>
      <br>
      <%= Entity.supra.email %>
    </p>
    <p>
      D. Št.: <%= Entity.supra.vat_id_formatted %>
      <br>
      Matična št.: <%= Entity.supra.registration_number %>
      <br>
      TRR: <%= Entity.supra.iban.prettify %>
    </p>
  </header>

  <div class="recipient">
    <p>
      <strong><%= invoice.customer %></strong>
      <br>
      <%= invoice.customer.address %>
      <br>
      <%= invoice.customer.post %>
    </p>
  </div>

  <div class="details">
    <p>
      <% if invoice.customer.vat_id? %>
        D.Št./ID št. za DDV kupca: <strong><%= invoice.customer.vat_id_formatted %></strong>
        <br>
      <% end %>
      Kraj izdaje: <strong>Velenje</strong>
      <br>
      Datume izdaje: <strong><%= l invoice.created_at.to_date, format: :simple %></strong>
      <br>
      Rok plačila: <strong><%= l invoice.due_at, format: :simple %></strong>
    </p>
  </div>

  <h1>Račun <%= invoice.receipt_id %></h1>

  <div class="items">
    <table>
      <thead>
        <tr>
          <th>Prejemnik</th>
          <th>Artikel/Storitev</th>
          <th>Kol.</th>
          <th>EM</th>
          <th>Cena</th>
          <th>Popust</th>
          <th>Cena s popustom</th>
          <th>Skupaj brez DDV</th>
        </tr>
      </thead>
      <tbody>
        <% invoice.line_items.each do |li| %>
          <tr>
            <td><%= li.entity_name %></td>
            <td><%= li.product %></td>
            <td><%= li.quantity %></td>
            <td><%= li.unit %></td>
            <td><%= number_to_currency li.price_per_item %></td>
            <td><%= number_to_percentage li.discount_percent || 0 %></td>
            <td><%= number_to_currency li.price_per_item_with_discount %></td>
            <td><%= number_to_currency li.subtotal %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="subtotals">
    <table>
      <thead>
        <tr>
          <th>Osnova za izračun davka</th>
          <th>DDV stopnja</th>
          <th>Davek</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <%= number_to_currency invoice.subtotal %>
          </td>
          <td><%= number_to_percentage invoice.tax_percent %></td>
          <td>
            <%= number_to_currency invoice.tax %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="totals">
    <p>
      Skupaj za plačilo:
      <strong><%= number_to_currency invoice.total %></strong>
    </p>
  </div>

  <div class="signature">
    <%= image_tag "darja_sig.png" %>
    <p>
      <strong>Fakturirala:</strong>
      <br>
      Darja Slapničar
    </p>
  </div>

  <div class="instructions">
    <p>Račun plačajte na TRR: <strong><%= Entity.supra.iban.prettify %></strong>, odprt pri <%= Entity.supra.bank.name %></p>
    <p>Pri plačilu računa se sklicujta na: <strong><%= invoice.payment_id_full %></strong>.</p>
    <p>Po izteku roka za plačilo zaračunavamo z zakonom določene zamudne obresti.</p>
    <p>Reklamacije upoštevamo, če so podane v 7 dneh od izstavitve računa.</p>
  </div>
</div>

app/views/admin/invoices/due.html.erb
<h2>
  Zapadli računi
  <% @years.each do |year| %>
    <small>
      <% if params[:year].to_i == year %>
        <%= year %>
      <% else %>
        <%= link_to year, year: year %>
      <% end %>
      |
    </small>
  <% end %>
  <small><%= link_to "Vsa leta", all: true %></small>
</h2>
<%= paginate @invoices %>
<table class="table rowlinks">
  <thead>
    <tr>
      <th>ID</th>
      <th>Stranka</th>
      <th>Izdan</th>
      <th>Rok</th>
      <th>Plačan</th>
      <th>Znesek</th>
      <th>Opomin</th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td>
          <%= link_to "", admin_invoice_path(invoice) %>
          <%= invoice.receipt_id %></td>
        <td><%= invoice.customer %></td>
        <td><%= l invoice.created_at, format: :simple %></td>
        <td><%= l invoice.due_at, format: :simple %></td>
        <td>
          <% if invoice.paid? %>
            <%= l invoice.paid_at, format: :simple %></td>
          <% elsif invoice.due? %>
            <span class="label label-danger"><%= invoice.late_days %> dni</span>
          <% end %>
        <td><%= number_to_currency invoice.total %></td>
        <td><%= button_to "Pošlji", email_due_admin_invoice_path(invoice), method: :post, class: 'btn btn-xs btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th>
        <%= @invoices.count %>
        računov
      </th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th><%= number_to_currency @invoices.to_a.sum(&:total) %></th>
    </tr>
  </tfoot>
</table>
<%= paginate @invoices %>

app/views/admin/invoices/eenvelope.xml.erb
<%= raw @eenvelope %>

app/views/admin/invoices/einvoice.xml.erb
<%= raw @einvoice %>

app/views/admin/invoices/print_wizard.html.erb
<h2>
  Tiskanje računov
  <i class="glyphicon glyphicon-print"></i>
</h2>

<div class="panel panel-default">
  <div class="panel-body">
    <%= form_tag print_all_admin_invoices_path, method: :get, class: 'form-inline print_invoices' do %>
      <div class="form-group">
        <%= number_field_tag :gte, @gte, {class: 'form-control', placeholder: 'Od Ref. Št.'} %>
        &mdash;
        <%= number_field_tag :lte, @lte, {class: 'form-control', placeholder: 'Do Ref. Št.'} %>
        /
        <%= number_field_tag :year, Time.now.year, {class: 'form-control', placeholder: 'Leto'} %>
      </div>
      <div class="form-group" style="margin-left: 25px;">
        <label>
          <%= check_box_tag :include_einvoiced %>
          Vključi prejemnike e-računov
        </label>
      </div>
      <div class="form-group pull-right">
        <%= submit_tag "Natisni", class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/invoices/show.html.erb
<h1>
  Račun <%= @invoice.receipt_id %>
  <small class="muted">
    za <%= link_to @invoice.customer, [:admin, @invoice.customer] %>
  </small>
  <% if @invoice.paid? %>
    <small class="label label-success pull-right">Plačan</small>
  <% elsif @invoice.reversed? %>
    <small class="label label-primary pull-right">Storniran</small>
  <% else %>
    <small class="label label-danger pull-right">Odprt</small>
  <% end %>
</h1>

<div class="row">
  <div class="col-xs-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <strong>Skupaj brez DDV:</strong>
        <p>
          <%= number_to_currency @invoice.subtotal %>
        </p>
        <strong>DDV:</strong>
        <p>
          <%= number_to_percentage @invoice.tax_percent %>
        </p>
        <strong>Davek:</strong>
        <p>
          <%= number_to_currency @invoice.tax %>
        </p>
        <strong>Skupaj za plačilo:</strong>
        <p>
          <%= number_to_currency @invoice.total %>
        </p>
        <hr>
        <strong>Kreiran:</strong>
        <p>
          <%= l @invoice.created_at %>
        </p>
        <strong>Osvežen:</strong>
        <p>
          <%= l @invoice.updated_at %>
        </p>
        <hr>
        <strong>Rok plačila:</strong>
        <p>
          <%= l @invoice.due_at, format: :simple %>
        </p>
        <% if @invoice.reversed? %>
          <strong>Storniran:</strong>
          <p>
            <%= l @invoice.reversed_at, format: :simple %>
            <% if @invoice.reverse_reason? %>
              <br>
              <small class="muted"><%= @invoice.reverse_reason %></small>
            <% end %>
          </p>
        <% elsif @invoice.paid? %>
          <strong>Plačan:</strong>
          <p>
            <%= l @invoice.paid_at, format: :simple %>
          </p>
        <% elsif @invoice.due? %>
          <strong>Zamuja:</strong>
          <p>
            <span class="label label-danger"><%= @invoice.late_days %> dni</span>
          </p>
        <% end %>
        <hr>
        <p>
          <%= link_to print_admin_invoice_path(@invoice), class: 'btn btn-default' do %>
            <i class="glyphicon glyphicon-print"></i>
            Natisni
          <% end %>
          <%= link_to pdf_admin_invoice_path(@invoice), class: 'btn btn-default' do %>
            <i class="glyphicon glyphicon-export"></i>
            PDF
          <% end %>
          <% link_to einvoice_admin_invoice_path(@invoice, format: :xml), class: 'btn btn-default' do %>
            <i class="glyphicon glyphicon-indent-left"></i>
            E-Račun XML
          <% end %>
          <%= link_to einvoice_admin_invoice_path(@invoice, format: :xml, style: true), class: 'btn btn-default' do %>
            <i class="glyphicon glyphicon-file"></i>
            E-Račun
          <% end %>
          <%= link_to eenvelope_admin_invoice_path(@invoice, format: :xml, style: true), class: 'btn btn-default' do %>
            <i class="glyphicon glyphicon-envelope"></i>
            E-ovojnica
          <% end %>
        </p>
        <% if @invoice.customer.billing_email %>
          <p>
            <%= link_to email_admin_invoice_path(@invoice), method: :post, class: 'btn btn-default', "data-confirm": "Ali ste prepričani da želite poslati račun na #{@invoice.customer.billing_email}?" do %>
              <i class="glyphicon glyphicon-envelope"></i>
              Pošlji račun
            <% end %>
            <% if @invoice.due? %>
              <%= link_to email_due_admin_invoice_path(@invoice), method: :post, class: 'btn btn-default', "data-confirm": "Ali ste prepričani da želite poslati opomin na #{@invoice.customer.billing_email}?" do %>
                <i class="glyphicon glyphicon-envelope"></i>
                Pošlji opomin
              <% end %>
           <% end %>
          </p>
        <% end %>
        <% if @invoice.events.any? %>
          <hr>
          <%= render 'events/events', events: @invoice.events %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Naročnik</h3>
      </div>
      <div class="panel-body">
        <%= render "admin/customers/fields", resource: @invoice.customer %>
      </div>
    </div>
    <% if @invoice.paid? || @invoice.statement_entries.any? %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Plačilo</h3>
        </div>
        <div class="panel-body">
          <% if @invoice.statement_entries.empty? %>
            <strong>Ref. št.:</strong>
            <p>
              <%= @invoice.bank_reference %>
            </p>
            <strong>Znesek:</strong>
            <p>
              <%= number_to_currency @invoice.paid_amount %>
            </p>
            <% if @invoice.bank_data.present? %>
              <strong>Podatki:</strong>
              <p>
                <small><%= simple_format @invoice.bank_data %></small>
              </p>
            <% end %>
          <% else %>
            <div class="statement-entry">
              <% @invoice.statement_entries.each do |entry| %>
                <p>
                  <%= link_to [:admin, entry] do %>
                    <code><%= entry.bank_reference %></code>
                  <% end %>
                  <%= l entry.date, format: :simple %>
                  &mdash;
                  <strong><%= number_to_currency entry.amount %></strong>
                  <br>
                  <small class="muted"><%= entry.account_holder %></small>
                </p>
              <% end %>
            </div>
          <% end %>
        </div>
        <% unless @invoice.balance == 0 %>
          <div class="panel-footer">
            <strong>Stanje</strong>
            <% if @invoice.balance > 0 %>
              <span class="label label-success">
                +<%= number_to_currency @invoice.balance %>
              </span>
            <% else %>
              <span class="label label-danger">
                <%= number_to_currency @invoice.balance %>
              </span>
            <% end %>
          </div>
        <% end %>
      </div>
    <% elsif !@invoice.reversed? %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Storniranje</h3>
        </div>
        <div class="panel-body">
          <%= simple_form_for @invoice, url: reverse_admin_invoice_path, method: :put, html: {class: 'form-inline'} do |f| %>
            <%= f.input :reverse_reason, label: false, placeholder: "Razlog za storniranje", as: :text, class: 'form-control' %>
            <div class="form-group pull-right">
              <%= f.submit "Storniraj", class: 'btn btn-default' %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="panel panel-default" style="margin-bottom: 150px;">
  <div class="panel-heading">
    <h3 class="panel-title">Postavke</h3>
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th>Entiteta</th>
          <th>Produkt</th>
          <th>Revija</th>
          <th>Kol.</th>
          <th>ME</th>
          <th>Cena</th>
          <th>Pop. %</th>
          <th>Cena s pop.</th>
          <th>Znesek</th>
          <th>Davek %</th>
          <th>Davek</th>
          <th>Za plačilo</th>
        </tr>
      </thead>
      <tbody>
        <% @invoice.line_items.each do |li| %>
          <tr>
            <td><%= li.entity_name %></td>
            <td><%= li.product %></td>
            <td><%= li.issue %></td>
            <td><%= li.quantity %></td>
            <td><%= li.unit %></td>
            <td><%= number_to_currency li.price_per_item %></td>
            <td><%= number_to_percentage li.discount_percent || 0 %></td>
            <td><%= number_to_currency li.price_per_item_with_discount %></td>
            <td><%= number_to_currency li.subtotal %></td>
            <td><%= number_to_percentage li.tax_percent %></td>
            <td><%= number_to_currency li.tax %></td>
            <td><%= number_to_currency li.total %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>